### ISSUE TITLE
Is this missing envifying process.env.NODE_ENV in production mode?

### ISSUE THREAD

**Issue by gaearon** [alexkuz/flask-react-boilerplate#2]
React uses `process.env.NODE_ENV` to switch into production mode, but it seems that [env variables](https://github.com/alexkuz/flask-react-boilerplate/blob/376ee7a5a35b52beb3e40fceffef4dc6e2da5084/webpack.base.config.js#L41-L46) don't include it.

Maybe it makes sense to change `__CURRENT_ENV__` to be called `NODE_ENV`? Or else `NODE_ENV` to alias it.

**Comment by alexkuz** [comment]
@gaearon Quite possible. I would rather just leave NODE_ENV - not sure if we need these variables at all.

**Comment by gaearon** [comment]
+1 on leaving just `NODE_ENV`
